stages:
  - build
  - package
  - docker

before_script:
  - export SERVER_NAMESPACE=github.com/servicelab

build:
  stage: build
  image: golang:1.10
  script:
    - mkdir -p /go/src/$SERVER_NAMESPACE
    - export GOPATH=/go
    - ln -s $CI_PROJECT_DIR /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
    - cd /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
    - export GOBIN=$GOPATH/bin
    - export PATH=$PATH:$GOPATH/bin
    - make release -j 6
  artifacts:
    paths:
      - dist
    expire_in: 30 mins
  tags:
    - docker

docker:
  stage: docker
  image: servicelaborg/docker:latest
  only:
    - tags
    - triggers
  services:
    - docker:dind
  script:
    - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
    - chmod 555 manifest-tool
    - make images -j 4
    - ./dist/tamtam-linux-amd64 version
    - docker run --rm servicelaborg/tamtam:1-linux-amd64 version
      #- ./manifest-tool push from-spec spec.yaml

macos:
  stage: package
  image: alpine:3.7
  only:
    - tags
    - triggers
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist/tamtam-darwin-amd64 ./tamtam
  artifacts:
    name: "$CI_PROJECT_NAME-v1.0.0-SNAPSHOT-$CI_JOB_NAME"
    paths:
      - tamtam

linux-amd64:
  stage: package
  image: alpine:3.7
  only:
    - tags
    - triggers
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist/tamtam-linux-amd64 ./tamtam
  artifacts:
    name: "$CI_PROJECT_NAME-v1.0.0-SNAPSHOT-$CI_JOB_NAME"
    paths:
      - tamtam

linux-386:
  stage: package
  image: alpine:3.7
  only:
    - tags
    - triggers
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist/tamtam-linux-386 ./tamtam
  artifacts:
    name: "$CI_PROJECT_NAME-v1.0.0-SNAPSHOT-$CI_JOB_NAME"
    paths:
      - tamtam

linux-arm:
  stage: package
  image: alpine:3.7
  only:
    - tags
    - triggers
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist/tamtam-linux-arm ./tamtam
  artifacts:
    name: "$CI_PROJECT_NAME-v1.0.0-SNAPSHOT-$CI_JOB_NAME"
    paths:
      - tamtam

linux-arm64:
  stage: package
  image: alpine:3.7
  only:
    - tags
    - triggers
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist/tamtam-linux-arm64 ./tamtam
  artifacts:
    name: "$CI_PROJECT_NAME-v1.0.0-SNAPSHOT-$CI_JOB_NAME"
    paths:
      - tamtam

windows:
  stage: package
  image: alpine:3.7
  only:
    - tags
    - triggers
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist/tamtam-windows-amd64 ./tamtam.exe
  artifacts:
    name: "$CI_PROJECT_NAME-v1.0.0-SNAPSHOT-$CI_JOB_NAME"
    paths:
      - tamtam.exe

