stages:
  - build
  - release

before_script:
  - export SERVER_NAMESPACE=github.com/servicelab
  - mkdir -p /go/src/$SERVER_NAMESPACE
  - export GOPATH=/go
  - cp -R $CI_PROJECT_DIR /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
  - cd /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:$GOPATH/bin

build:
  stage: build
  image: golang:1.10
  script:
    - make cross
  tags:
    - docker

docker:
  stage: release
  image: docker
  only:
    - tags
    - triggers
  services:
    - docker:dind
  script:
    - apk add --no-cache make curl bash git go
    - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
    - chmod 555 manifest-tool
    - make login
    - curl -sL https://git.io/goreleaser | bash
    - ./manifest-tool push from-spec spec.yaml

