stages:
  - build
  - release
  - docker

before_script:
  - export SERVER_NAMESPACE=github.com/servicelab
  - mkdir -p /go/src/$SERVER_NAMESPACE
  - export GOPATH=/go
  - ln -s $CI_PROJECT_DIR /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
  - cd /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:$GOPATH/bin

build:
  stage: build
  image: golang:1.10
  script:
    - make cross
  tags:
    - docker

release:
  stage: release
  image: golang:1.10
  only:
    - tags
    - triggers
  script:
    - curl -sL https://git.io/goreleaser | bash
  artifacts:
    paths:
      - dist/
    expire_in: 30 mins
  tags:
    - docker

docker:
  stage: docker
  image: docker
  only:
    - tags
    - triggers
  services:
    - docker:dind
  script:
    - apk add --no-cache make
    - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
    - chmod 555 manifest-tool
    - make images
    - ./manifest-tool push from-spec spec.yaml

