stages:
  - build
  - push
  # - deploy

binaries:
  stage: build
  image: golang:1.9
  script:
    - curl https://glide.sh/get | sh
    - export SERVER_NAMESPACE=github.com/eelcocramer
    - mkdir -p /go/src/$SERVER_NAMESPACE
    - export GOPATH=/go
    - ln -s $CI_PROJECT_DIR /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
    - cd /go/src/$SERVER_NAMESPACE/$CI_PROJECT_NAME
    - export GOBIN=$GOPATH/bin
    - export PATH=$PATH:$GOPATH/bin
    - ./dist.sh
  artifacts:
    paths:
      - dist/
  cache:
    key: go-cache
    paths:
      - .godeps
  tags:
    - docker
