before:
  hooks:
    - make clean

builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/servicelab/{{.ProjectName}}/cmd.Version={{.Version}} -X github.com/servicelab/{{.ProjectName}}/cmd.BuildTime={{.Date}} -X github.com/servicelab/{{.ProjectName}}/cmd.GitHash={{.Commit}}
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - 386
  - arm64
  - arm
  ignore:
  - goos: darwin
    goarch: arm
  - goos: darwin
    goarch: arm64
  - goos: darwin
    goarch: "386"
  - goos: windows
    goarch: arm
  - goos: windows
    goarch: arm64

archive:
  replacements:
    darwin: macos
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: servicelab
    name: tamtam
  prerelease: true

  #dockers:
  #  - goos: linux
  #    goarch: amd64
  #    binary: tamtam
  #    image: servicelaborg/tamtam
  #    dockerfile: Dockerfile
  #    tag_templates:
  #      - "{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  #
  #  - goos: linux
  #    goarch: arm64
  #    image: servicelaborg/tamtam
  #    binary: tamtam
  #    dockerfile: Dockerfile
  #    tag_templates:
  #      - "{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  #
  #  - goos: linux
  #    goarch: arm
  #    goarm: "6"
  #    image: servicelaborg/tamtam
  #    binary: tamtam
  #    dockerfile: Dockerfile
  #    tag_templates:
  #      - "{{ .Major }}-{{ .Os }}-{{ .Arch }}"
  #      - "{{ .Major }}.{{ .Minor }}-{{ .Os }}-{{ .Arch }}"
  #      - "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-{{ .Os }}-{{ .Arch }}"
  #      - "latest-{{ .Os }}-{{ .Arch }}"

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
