[[constraint]]
  branch = "master"
  name = "github.com/CrowdSurge/banner"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "~1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/clockworksoul/smudge"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.0.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.11.1"

[prune]
  go-tests = true
  unused-packages = true
